### PR TITLE
DTSPO-9049 - Fix ptl backend

### PR DESCRIPTION
**Pull request by endakelly**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPO-9049

### Change description ###
Remove condition that points ptl environment to prod backend resource group

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timja — APPROVED** [review]
this not going to break anything anywhere else? or need a state file migration?

**Comment by endakelly** [comment]
> this not going to break anything anywhere else? or need a state file migration?

A good point, I haven't checked. Alternatively to merging this into master, we could merge the publishPlanResults changes from master into DTSPO-2880_sds_ptl so sds-jenkins-infrastructure continues to work and has the terraform plan published

**Comment by timja** [comment]
> > this not going to break anything anywhere else? or need a state file migration?
> 
> A good point, I haven't checked. Alternatively to merging this into master, we could merge the publishPlanResults changes from master into DTSPO-2880_sds_ptl so sds-jenkins-infrastructure continues to work and has the terraform plan published

It would be better to get this mainlined rather than maintaining branches, we can always fix forward if needed

**Comment by endakelly** [comment]
A quick search on github and azure suggests it's only sds-jenkins-infrastructure and the dynatrace stage in azure-platform-terraform that would be affected https://dev.azure.com/hmcts/CNP/_build/results?buildId=241688&view=logs&j=1f1c515e-fd4c-59cd-570a-8c47feca6bfb&t=4de6fb99-6358-58ed-d8a1-06f5fd0aa74f&l=12

**Comment by timja** [comment]
can you check the azure-platform-terraform one then?

**Pull request merged**
